import Head from "next/head";
import Posts from "../components/Posts";
import { sanityClient } from "../sanity";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="font-rany">
        <h1 className="font-bold text-4xl md:text-6xl xl:text-9xl text-center max-w-2xl mx-auto mt-16">
          My Blog
        </h1>
        <div className="h-[2px] bg-slate-300 my-8 md:my-16 max-w-2xl mx-4 md:mx-auto" />
        <Posts posts={posts} />
      </section>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"] {
    _id,
    _createdAt,
    title, 
    author -> {
     name, 
     image
    },
    description,
    mainImage, 
    slug,
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
